### ISSUE TITLE
Setup the backend and connect to database

### ISSUE THREAD

**Issue by Leeoku** [Leeoku/pearish#12]
Initial start flask+mongo

**Comment by Leeoku** [comment]
Initial start to use flask connect to mongo

**Comment by OmarMoghazy** [comment]
I prepared a react application on the react-app branch (for if we decide are gonna use react) and there's a an api folder with Ken and Andy's code. 
@ryanjcohen I need you to set up flask with MongoDB and just connect to the database using the connection key I provided. That should be a simple task I think.

These resources may help you:
https://www.youtube.com/watch?v=rE_bJl2GAY8
https://blog.miguelgrinberg.com/post/how-to-create-a-react--flask-project

**Comment by OmarMoghazy** [comment]
The connection to the database is ready thanks to @ryanjcohen . The next step is actually configuring the react app to link to flask when it gets a request. I will work on that soon.

**Comment by Leeoku** [comment]
Will mark this as completed and will break up ur items into smaller peices
