### ISSUE TITLE
Main page (or landing page?) layout mockup

### ISSUE THREAD

**Issue by Leeoku** [Leeoku/pearish#13]
Do a wireframe/paper design or something showing how our site will look. For now we will use this [receipt as our sample](https://ocr.space/receiptscanning). But we will want to add functionality for uploading your own image (PC first).

**Comment by maazq210** [comment]
[Pearish.pdf](https://github.com/Leeoku/pearish/files/4795312/Pearish.pdf)

**Comment by Leeoku** [comment]
Let's have a discussion with tyler first

**Comment by maazq210** [comment]
[PearishMk2.pdf](https://github.com/Leeoku/pearish/files/4806470/PearishMk2.pdf)

**Comment by maazq210** [comment]
[PearishMk2v1.2.pdf](https://github.com/Leeoku/pearish/files/4806481/PearishMk2v1.2.pdf)

**Comment by Leeoku** [comment]
Good wireframe start, start coding! (I believe you guys chose react)

**Comment by maazq210** [comment]
So for UI we're gonna be using semantic rather than bootstrap since it's native to react. I also set up a react-router-dom in node_modules so it should make loading in browser better. there are three pages under the components folder I added to src Home, About, and Login.

**Comment by Leeoku** [comment]
Routes/layout complete. May rework routes in second iteration
